# screen manager defined to connect all the screens
<KQScreenManager>:
    id: _screen_manager
    current: 'login_screen'
    LoginScreen:
        screen_manager: _screen_manager
    HomeScreen:
        screen_manager: _screen_manager
    ActivityScreen:
        screen_manager: _screen_manager
    LocationScreen:
        screen_manager: _screen_manager
    MealScreen:
        screen_manager: _screen_manager