<LocationScreenLayout>
    Label:
        size_hint_x: .2
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            Button:
        BoxLayout:
            size_hint_y: .425

<LocationScreen@Screen>:
    name: 'location_screen'
    screen_manager: self.screen_manager

    LocationScreenLayout:
        screen_manager: root.screen_manager

    SideBar:
        screen_manager: root.screen_manager
